// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackerCore.Models;

namespace TrackerCore.Migrations
{
    [DbContext(typeof(TravellerDBContext))]
    [Migration("20191012134422_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("TrackerCore.Models.Ship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipClassID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("currentCargo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("currentCredits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("currentFuel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("currentHighPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("currentLowPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("currentMidPassengers")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("TrackerCore.Models.ShipClass", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cargo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fuel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jump")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maneuver")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MidPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tonnage")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("ShipClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
