// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipTracker.Models;

namespace ShipTracker.Migrations
{
    [DbContext(typeof(TravellerDBContext))]
    [Migration("20190823172608_ship_and_shipclass")]
    partial class ship_and_shipclass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ShipTracker.Models.ShipClasses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cargo");

                    b.Property<string>("ClassName");

                    b.Property<string>("Classification");

                    b.Property<int>("Fuel");

                    b.Property<int>("HighPassengers");

                    b.Property<int>("Jump");

                    b.Property<int>("LowPassengers");

                    b.Property<int>("Meneauver");

                    b.Property<int>("MidPassengers");

                    b.Property<int>("Power");

                    b.Property<int>("Tonnage");

                    b.HasKey("id");

                    b.ToTable("ShipClass");
                });

            modelBuilder.Entity("ShipTracker.Models.Ships", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("ShipClassID");

                    b.Property<int>("currentCargo");

                    b.Property<int>("currentCredits");

                    b.Property<int>("currentFuel");

                    b.Property<int>("currentHighPassengers");

                    b.Property<int>("currentLowPassengers");

                    b.Property<int>("currentMidPassengers");

                    b.HasKey("id");

                    b.ToTable("Ship");
                });
#pragma warning restore 612, 618
        }
    }
}
